export type ModuleCategory = "food" | "movement" | "space" | "mind";
export type ModuleEnergyLevel = "low" | "mid" | "high";

export type LifeModule = {
  id: string;
  name: string;
  category: ModuleCategory;
  duration: number;
  energyLevel: ModuleEnergyLevel;
  starter?: string;
  sensoryHooks?: string[];
  instructions: string[];
  tips?: string[];
};

export const moduleLibrary: LifeModule[] = [
  {
    id: "mod_slow_cooking",
    name: "慢速做饭",
    category: "food",
    duration: 45,
    energyLevel: "low",
    instructions: [
      "打开厨房灯，把手机放到客厅充电。",
      "选一种需要慢慢切的蔬菜，比如土豆、胡萝卜或蘑菇。",
      "把菜洗净后切成大小接近的小块。",
      "用小火煮或炒，不同时做别的事。",
      "盛到真正的碗里，坐下吃完前不要站起来。",
    ],
  },
  {
    id: "mod_rice_bowl",
    name: "热饭碗",
    category: "food",
    duration: 20,
    energyLevel: "low",
    instructions: [
      "把一份米饭加热到冒热气。",
      "煎一个鸡蛋或加一份现成蛋白质。",
      "放一勺酱油、芝麻油或辣酱。",
      "坐在桌前吃，不边走边吃。",
    ],
  },
  {
    id: "mod_simple_noodle",
    name: "清汤面",
    category: "food",
    duration: 18,
    energyLevel: "low",
    instructions: [
      "烧一锅水，同时拿出面、青菜和鸡蛋。",
      "水开后先下面，再放青菜。",
      "把鸡蛋打进锅里或另煎一个蛋。",
      "碗里放盐、酱油和一点油，再倒入热汤。",
    ],
  },
  {
    id: "mod_cut_fruit_plate",
    name: "切水果盘",
    category: "food",
    duration: 15,
    energyLevel: "low",
    instructions: [
      "选两种水果，优先选需要清洗和切开的。",
      "把砧板和水果刀放好，不站在水槽边随便吃。",
      "切成入口大小，摆到一个盘子里。",
      "倒一杯水，坐下吃完。",
    ],
  },
  {
    id: "mod_warm_milk",
    name: "热牛奶",
    category: "food",
    duration: 10,
    energyLevel: "low",
    instructions: [
      "拿一个马克杯，倒入牛奶或豆奶。",
      "微波炉加热 60 到 90 秒。",
      "加一小勺蜂蜜或不加任何东西。",
      "站在厨房喝前三口，再带到座位上喝完。",
    ],
  },
  {
    id: "mod_toast_plate",
    name: "烤吐司",
    category: "food",
    duration: 12,
    energyLevel: "low",
    instructions: [
      "拿两片吐司放进烤箱或平底锅。",
      "准备一种涂抹物，比如黄油、花生酱或果酱。",
      "吐司变脆后切成两半。",
      "放到盘子里，配一杯热饮。",
    ],
  },
  {
    id: "mod_tea_and_snack",
    name: "茶和点心",
    category: "food",
    duration: 15,
    energyLevel: "low",
    instructions: [
      "烧一壶水，选一个真正想用的杯子。",
      "泡茶、咖啡或无咖啡因热饮。",
      "拿一份小点心，不直接拿整包。",
      "坐下吃喝 10 分钟，不刷短视频。",
    ],
  },
  {
    id: "mod_vegetable_soup",
    name: "蔬菜汤",
    category: "food",
    duration: 35,
    energyLevel: "low",
    instructions: [
      "选三种蔬菜，洗好后切成小块。",
      "锅里放水或高汤，先放最硬的蔬菜。",
      "小火煮 20 分钟，中途只搅拌两次。",
      "最后加盐和一点胡椒。",
      "盛一碗，剩下的装盒冷藏。",
    ],
  },
  {
    id: "mod_grocery_walk",
    name: "买晚餐材料",
    category: "food",
    duration: 35,
    energyLevel: "mid",
    instructions: [
      "写下只买三样东西：主食、蛋白质、蔬菜。",
      "带一个购物袋出门，不打开外卖软件。",
      "进店后按清单买，不临时加零食。",
      "回家后立刻把材料放到台面上。",
    ],
  },
  {
    id: "mod_one_pan_dinner",
    name: "一锅晚餐",
    category: "food",
    duration: 35,
    energyLevel: "mid",
    instructions: [
      "选一个平底锅或汤锅，只用这一个锅。",
      "先处理蛋白质，再处理蔬菜。",
      "所有食材进锅后设置 15 分钟计时。",
      "等待时清掉砧板和刀。",
      "直接从锅里分装到碗里。",
    ],
  },
  {
    id: "mod_market_salad",
    name: "超市沙拉",
    category: "food",
    duration: 20,
    energyLevel: "low",
    instructions: [
      "买一包洗好的生菜或沙拉菜。",
      "再买一种熟食蛋白质，比如鸡胸、豆腐或鸡蛋。",
      "回家后把菜倒进大碗，不用原包装吃。",
      "加油醋汁或酸奶酱，拌 30 秒。",
    ],
  },
  {
    id: "mod_dumpling_boiling",
    name: "煮饺子",
    category: "food",
    duration: 18,
    energyLevel: "low",
    instructions: [
      "烧一锅水，拿出 10 到 15 个冷冻饺子。",
      "水开后下饺子，用勺背轻轻推开。",
      "加两次冷水，等饺子浮起。",
      "调一小碟醋或酱油，坐下吃。",
    ],
  },
  {
    id: "mod_egg_fried_rice",
    name: "蛋炒饭",
    category: "food",
    duration: 20,
    energyLevel: "mid",
    instructions: [
      "把剩饭打散，鸡蛋打进碗里。",
      "热锅放油，先炒鸡蛋再放米饭。",
      "加一小把葱花或冷冻蔬菜。",
      "最后加盐或酱油，关火后再拌 10 秒。",
    ],
  },
  {
    id: "mod_breakfast_for_dinner",
    name: "早餐当晚餐",
    category: "food",
    duration: 25,
    energyLevel: "low",
    instructions: [
      "选一个早餐主食，比如吐司、燕麦或鸡蛋。",
      "加一份水果或酸奶。",
      "把所有东西放到同一个托盘上。",
      "坐到餐桌或窗边吃，不在床上吃。",
    ],
  },
  {
    id: "mod_slow_chopping",
    name: "慢慢切菜",
    category: "food",
    duration: 25,
    energyLevel: "low",
    instructions: [
      "洗一根黄瓜、一个苹果或一根胡萝卜。",
      "把砧板擦干，刀放在右手边。",
      "用比平时慢一半的速度切完。",
      "切好后直接吃，或放进明天的盒子里。",
    ],
  },
  {
    id: "mod_hot_porridge",
    name: "热粥",
    category: "food",
    duration: 30,
    energyLevel: "low",
    instructions: [
      "淘半杯米，放入锅中加四倍水。",
      "开火煮沸后转小火。",
      "每 8 分钟搅一次，避免糊底。",
      "加盐、榨菜或一个鸡蛋。",
      "关火后静置 3 分钟再盛出。",
    ],
  },
  {
    id: "mod_sandwich_make",
    name: "做三明治",
    category: "food",
    duration: 15,
    energyLevel: "low",
    instructions: [
      "拿两片面包放在盘子上。",
      "加入一种蛋白质和一种蔬菜。",
      "涂少量酱，不让面包湿透。",
      "对半切开，装盘后再吃。",
    ],
  },
  {
    id: "mod_freezer_rescue",
    name: "清冰箱一餐",
    category: "food",
    duration: 30,
    energyLevel: "mid",
    instructions: [
      "打开冰箱，只拿出三样快过期的食材。",
      "把不能一起煮的食材放回去。",
      "剩下的切小块，统一放进锅里炒或煮。",
      "做好后把台面擦干净。",
    ],
  },
  {
    id: "mod_bento_pack",
    name: "装明天便当",
    category: "food",
    duration: 25,
    energyLevel: "mid",
    instructions: [
      "拿出一个饭盒，确认盖子能合上。",
      "放入主食，占饭盒一半。",
      "加一份蛋白质和一份蔬菜。",
      "等热气散掉再盖盖子。",
      "贴一张便签写上明天中午吃。",
    ],
  },
  {
    id: "mod_drink_water_reset",
    name: "喝水重置",
    category: "food",
    duration: 8,
    energyLevel: "low",
    instructions: [
      "洗一个杯子或水瓶。",
      "倒满温水，不加饮料粉。",
      "站在原地喝掉三分之一。",
      "把剩下的水放到接下来会坐的位置旁边。",
    ],
  },
  {
    id: "mod_night_walk",
    name: "夜间散步",
    category: "movement",
    duration: 30,
    energyLevel: "low",
    instructions: [
      "穿一双不用系很久的鞋。",
      "带钥匙和手机，不戴耳机或只戴一只。",
      "绕最近的街区走 20 分钟。",
      "回家前在楼下或门口站 2 分钟。",
    ],
  },
  {
    id: "mod_one_block_walk",
    name: "走一圈楼下",
    category: "movement",
    duration: 12,
    energyLevel: "low",
    instructions: [
      "换上外出的鞋，不更换整套衣服。",
      "走到楼下或门口。",
      "绕最近的一圈走完，不临时加路线。",
      "回家后喝几口水。",
    ],
  },
  {
    id: "mod_stair_climb",
    name: "爬楼梯",
    category: "movement",
    duration: 10,
    energyLevel: "mid",
    instructions: [
      "走到楼梯间，确认照明正常。",
      "慢慢爬 3 层楼或走 5 分钟。",
      "扶着扶手下楼。",
      "回到房间后坐下休息 2 分钟。",
    ],
  },
  {
    id: "mod_stretch_floor",
    name: "地板拉伸",
    category: "movement",
    duration: 15,
    energyLevel: "low",
    instructions: [
      "在地上铺一条毛巾或瑜伽垫。",
      "坐下后先向前折叠 30 秒。",
      "左右各转肩 10 次。",
      "躺下抱膝 1 分钟。",
      "起身前慢慢坐起，不立刻站起来。",
    ],
  },
  {
    id: "mod_shoulder_release",
    name: "肩颈放松",
    category: "movement",
    duration: 8,
    energyLevel: "low",
    instructions: [
      "坐直，把双脚踩到地上。",
      "肩膀向后绕 10 次。",
      "头向左停 20 秒，再向右停 20 秒。",
      "双手交叉向前推，背部停 30 秒。",
    ],
  },
  {
    id: "mod_kitchen_squat",
    name: "厨房深蹲",
    category: "movement",
    duration: 8,
    energyLevel: "mid",
    instructions: [
      "站在厨房台面前，双脚与肩同宽。",
      "双手轻扶台面。",
      "慢慢做 10 个深蹲。",
      "喝一口水，再做第二组 10 个。",
    ],
  },
  {
    id: "mod_music_walk_home",
    name: "听歌走路",
    category: "movement",
    duration: 25,
    energyLevel: "low",
    instructions: [
      "选一张专辑或一个 20 分钟歌单。",
      "穿鞋出门，路线只选熟悉街道。",
      "歌曲结束前不看社交软件。",
      "最后一首歌时往家走。",
    ],
  },
  {
    id: "mod_gentle_dance",
    name: "轻跳一首歌",
    category: "movement",
    duration: 6,
    energyLevel: "mid",
    instructions: [
      "清出脚边一平方米空间。",
      "播放一首 3 到 5 分钟的歌。",
      "只移动肩膀、手臂和脚步，不追求动作好看。",
      "歌曲结束后关掉音乐，坐下喘匀。",
    ],
  },
  {
    id: "mod_bike_short",
    name: "短程骑车",
    category: "movement",
    duration: 30,
    energyLevel: "mid",
    instructions: [
      "确认车灯、刹车和钥匙。",
      "选择一条 15 分钟内能返回的路线。",
      "骑到一个明确地点，比如便利店或公园门口。",
      "不进店也可以，停 2 分钟后返回。",
    ],
  },
  {
    id: "mod_bus_one_stop",
    name: "坐一站车",
    category: "movement",
    duration: 25,
    energyLevel: "low",
    instructions: [
      "查最近一班公交或地铁。",
      "只坐一站或两站，不设计复杂路线。",
      "下车后在站外站 3 分钟。",
      "从同一路线返回或步行回家。",
    ],
  },
  {
    id: "mod_park_loop",
    name: "公园小圈",
    category: "movement",
    duration: 35,
    energyLevel: "low",
    instructions: [
      "选择最近的公园或绿地。",
      "走到入口后只绕最小的一圈。",
      "路上找一个长椅坐 5 分钟。",
      "原路返回，不临时改成大路线。",
    ],
  },
  {
    id: "mod_grocery_errand",
    name: "带任务出门",
    category: "movement",
    duration: 30,
    energyLevel: "mid",
    instructions: [
      "写下一个要买的小东西，比如牛奶或纸巾。",
      "带购物袋和钥匙出门。",
      "直接走到最近的店。",
      "买完马上回家，不增加第二个任务。",
    ],
  },
  {
    id: "mod_window_breath",
    name: "窗边呼吸",
    category: "movement",
    duration: 7,
    energyLevel: "low",
    instructions: [
      "走到窗边或阳台门口。",
      "打开窗户 5 厘米或站在门边。",
      "慢慢吸气 4 秒，呼气 6 秒，重复 8 次。",
      "关窗前看一眼远处的固定物体。",
    ],
  },
  {
    id: "mod_laundry_walk",
    name: "洗衣顺路走",
    category: "movement",
    duration: 35,
    energyLevel: "mid",
    instructions: [
      "把一小篮衣服放进洗衣机。",
      "启动洗衣后立刻出门走 15 分钟。",
      "设置手机计时提醒。",
      "回来后把衣服晾上或转入烘干机。",
    ],
  },
  {
    id: "mod_morning_route_preview",
    name: "预走明早路线",
    category: "movement",
    duration: 25,
    energyLevel: "low",
    instructions: [
      "选明早要去的第一个地点。",
      "今晚只走到路线的第一个转角或车站。",
      "确认需要多久到达那里。",
      "回家后把钥匙和包放在门口附近。",
    ],
  },
  {
    id: "mod_fast_walk_three_songs",
    name: "快走三首歌",
    category: "movement",
    duration: 12,
    energyLevel: "mid",
    instructions: [
      "选三首节奏稳定的歌。",
      "第一首正常走，第二首加快脚步。",
      "第三首放慢速度往回走。",
      "结束后拉伸小腿 30 秒。",
    ],
  },
  {
    id: "mod_floor_core",
    name: "地板核心",
    category: "movement",
    duration: 12,
    energyLevel: "high",
    instructions: [
      "在地上铺垫子或毛巾。",
      "做 20 秒平板支撑，休息 20 秒。",
      "做 10 个卷腹。",
      "重复两轮，结束后躺平 1 分钟。",
    ],
  },
  {
    id: "mod_long_walk_water",
    name: "带水长走",
    category: "movement",
    duration: 50,
    energyLevel: "mid",
    instructions: [
      "装一瓶水，确认手机电量超过 30%。",
      "选择一个 25 分钟能到的地点。",
      "走到地点后喝水，坐 5 分钟。",
      "按原路线返回。",
    ],
  },
  {
    id: "mod_room_pacing",
    name: "室内踱步",
    category: "movement",
    duration: 10,
    energyLevel: "low",
    instructions: [
      "设置 10 分钟计时器。",
      "在房间里来回走，不看屏幕。",
      "每走到门口就转身。",
      "计时结束后停下，喝一口水。",
    ],
  },
  {
    id: "mod_body_scan_stand",
    name: "站立扫描",
    category: "movement",
    duration: 6,
    energyLevel: "low",
    instructions: [
      "站到墙边，后背轻轻靠墙。",
      "检查脚底、膝盖、肩膀和下巴的位置。",
      "每个部位停 10 秒。",
      "最后向上伸手一次，再放下。",
    ],
  },
  {
    id: "mod_drawer_reset",
    name: "整理一个抽屉",
    category: "space",
    duration: 20,
    energyLevel: "low",
    instructions: [
      "只打开一个抽屉，不碰其他柜子。",
      "把里面所有东西放到桌面。",
      "扔掉明显没用的纸和包装。",
      "把剩下的按常用和不常用放回去。",
    ],
  },
  {
    id: "mod_hot_bath",
    name: "热水澡",
    category: "space",
    duration: 20,
    energyLevel: "low",
    instructions: [
      "提前拿好干净衣服和毛巾。",
      "把浴室灯打开，水温调到偏热但不烫。",
      "洗澡时不带手机进浴室。",
      "出来后立刻穿好衣服，不站着刷手机。",
    ],
  },
  {
    id: "mod_bed_reset",
    name: "整理床面",
    category: "space",
    duration: 12,
    energyLevel: "low",
    instructions: [
      "把床上所有不是睡觉用的东西拿下来。",
      "抖开被子，铺平床单。",
      "枕头放回固定位置。",
      "把拿下来的东西放到一个篮子里。",
    ],
  },
  {
    id: "mod_desk_clear",
    name: "清空桌面",
    category: "space",
    duration: 18,
    energyLevel: "low",
    instructions: [
      "拍一张桌面照片，作为整理前记录。",
      "把杯子、垃圾和纸张分成三堆。",
      "只留下电脑、灯和一件需要做的事。",
      "用湿纸巾擦桌面中央。",
    ],
  },
  {
    id: "mod_sink_zero",
    name: "清空水槽",
    category: "space",
    duration: 20,
    energyLevel: "mid",
    instructions: [
      "戴上手套或卷起袖子。",
      "先洗杯子和筷子，再洗碗盘。",
      "把洗好的东西放到沥水架。",
      "最后冲洗水槽边缘。",
    ],
  },
  {
    id: "mod_entryway_reset",
    name: "门口重置",
    category: "space",
    duration: 15,
    energyLevel: "low",
    instructions: [
      "站在门口，看一眼鞋、包和钥匙。",
      "只留下明天要穿的一双鞋。",
      "钥匙放到固定碗或挂钩。",
      "把地上的袋子移到墙边。",
    ],
  },
  {
    id: "mod_clothes_chair",
    name: "衣服椅清空",
    category: "space",
    duration: 18,
    energyLevel: "low",
    instructions: [
      "把椅子上的衣服全部拿到床上。",
      "分成干净、待洗、明天还穿三类。",
      "待洗的放进洗衣篮。",
      "干净的挂起或叠好，只处理这一把椅子。",
    ],
  },
  {
    id: "mod_light_one_corner",
    name: "点亮一个角落",
    category: "space",
    duration: 15,
    energyLevel: "low",
    instructions: [
      "选一个今晚会待 10 分钟的角落。",
      "打开一盏台灯或移动一盏灯过去。",
      "移走角落里的垃圾和无关物品。",
      "放一杯水或一本书在手边。",
    ],
  },
  {
    id: "mod_fridge_shelf",
    name: "清一层冰箱",
    category: "space",
    duration: 20,
    energyLevel: "mid",
    instructions: [
      "只选冰箱里的一层。",
      "拿出这一层所有东西。",
      "扔掉过期或明显不能吃的。",
      "擦干这一层，再把剩下的放回去。",
    ],
  },
  {
    id: "mod_trash_round",
    name: "收一轮垃圾",
    category: "space",
    duration: 12,
    energyLevel: "low",
    instructions: [
      "拿一个垃圾袋，从房间门口开始。",
      "只收明显垃圾，不做分类整理。",
      "走完卧室、厨房和卫生间。",
      "把垃圾袋系好放到门口。",
    ],
  },
  {
    id: "mod_floor_visible",
    name: "露出地面",
    category: "space",
    duration: 20,
    energyLevel: "mid",
    instructions: [
      "选一块一平方米的地面。",
      "把地上的物品移到桌面或篮子里。",
      "扫掉可见灰尘和碎屑。",
      "在这块地面上站 10 秒确认清空。",
    ],
  },
  {
    id: "mod_candle_table",
    name: "餐桌一盏灯",
    category: "space",
    duration: 10,
    energyLevel: "low",
    instructions: [
      "清出餐桌的一角。",
      "放一盏小灯或点一支安全蜡烛。",
      "拿走桌上的外卖包装和空杯子。",
      "把今晚要吃或喝的东西放在那里。",
    ],
  },
  {
    id: "mod_bathroom_counter",
    name: "洗手台整理",
    category: "space",
    duration: 15,
    energyLevel: "low",
    instructions: [
      "把洗手台上的东西全部移到一侧。",
      "丢掉空瓶和用完的包装。",
      "擦干台面水渍。",
      "只放回牙刷、洗面奶和常用护肤品。",
    ],
  },
  {
    id: "mod_bag_unpack",
    name: "清空包",
    category: "space",
    duration: 15,
    energyLevel: "low",
    instructions: [
      "把包里的东西全部倒到桌上。",
      "扔掉票据、纸巾和包装。",
      "钥匙、钱包和证件放回包里。",
      "把不该在包里的东西放回原处。",
    ],
  },
  {
    id: "mod_phone_charging_station",
    name: "手机充电位",
    category: "space",
    duration: 10,
    energyLevel: "low",
    instructions: [
      "选一个离床至少两步远的位置。",
      "把充电线插好并固定。",
      "清掉旁边的杂物。",
      "今晚睡前把手机放在那里充电。",
    ],
  },
  {
    id: "mod_window_sill",
    name: "窗台清理",
    category: "space",
    duration: 15,
    energyLevel: "low",
    instructions: [
      "把窗台上的东西全部拿下来。",
      "用湿纸巾擦一遍窗台。",
      "只放回一件植物、杯子或小物。",
      "打开窗 3 分钟后关上。",
    ],
  },
  {
    id: "mod_paper_stack",
    name: "纸张三分法",
    category: "space",
    duration: 18,
    energyLevel: "low",
    instructions: [
      "把散落纸张集中到桌面。",
      "分成丢掉、待处理、需要保存三堆。",
      "立刻丢掉第一堆。",
      "待处理那堆夹起来放到显眼处。",
    ],
  },
  {
    id: "mod_pillowcase_change",
    name: "换枕套",
    category: "space",
    duration: 10,
    energyLevel: "low",
    instructions: [
      "拿一个干净枕套放到床上。",
      "取下旧枕套，直接放进洗衣篮。",
      "套上新枕套，拍平枕头。",
      "把枕头放回床头固定位置。",
    ],
  },
  {
    id: "mod_tea_station",
    name: "热饮角",
    category: "space",
    duration: 15,
    energyLevel: "low",
    instructions: [
      "选厨房或桌面的一小块区域。",
      "放上杯子、茶包或咖啡。",
      "把热水壶或保温杯放到旁边。",
      "清走这块区域的其他物品。",
    ],
  },
  {
    id: "mod_air_room",
    name: "房间换气",
    category: "space",
    duration: 12,
    energyLevel: "low",
    instructions: [
      "打开窗户或门，让空气流通。",
      "设置 10 分钟计时器。",
      "计时期间把地上两件东西归位。",
      "时间到后关窗，确认室温合适。",
    ],
  },
  {
    id: "mod_three_line_journal",
    name: "写三行日记",
    category: "mind",
    duration: 15,
    energyLevel: "low",
    instructions: [
      "拿纸笔或打开一个空白备忘录。",
      "第一行写今天发生的一件事实。",
      "第二行写身体现在的感觉。",
      "第三行写明天只需要做的一件小事。",
    ],
  },
  {
    id: "mod_brain_dump",
    name: "倒空脑袋",
    category: "mind",
    duration: 12,
    energyLevel: "low",
    instructions: [
      "设置 8 分钟计时器。",
      "把脑中所有待办逐条写下。",
      "不要整理顺序，不要判断重要性。",
      "时间到后圈出一个明天再看的项目。",
    ],
  },
  {
    id: "mod_ten_min_read",
    name: "读十分钟",
    category: "mind",
    duration: 10,
    energyLevel: "low",
    instructions: [
      "拿一本纸书或打开电子书。",
      "设置 10 分钟计时器。",
      "从当前页开始读，不回头选书。",
      "时间到后把页码记下来。",
    ],
  },
  {
    id: "mod_no_phone_timer",
    name: "无手机十分钟",
    category: "mind",
    duration: 10,
    energyLevel: "low",
    instructions: [
      "把手机放到另一个房间或包里。",
      "设置厨房计时器或电脑计时器。",
      "坐在椅子上，手边只留水。",
      "时间到后再决定要不要拿手机。",
    ],
  },
  {
    id: "mod_tomorrow_note",
    name: "写明早纸条",
    category: "mind",
    duration: 8,
    energyLevel: "low",
    instructions: [
      "拿一张便签或纸。",
      "写下明早第一件事。",
      "写下需要带走的一样东西。",
      "把纸贴在门口或电脑上。",
    ],
  },
  {
    id: "mod_message_one_person",
    name: "发一条消息",
    category: "mind",
    duration: 8,
    energyLevel: "low",
    instructions: [
      "选择一个不会让你紧张的人。",
      "只发送一句具体消息。",
      "不要解释太多，也不要立刻等回复。",
      "发完后把聊天窗口关掉。",
    ],
  },
  {
    id: "mod_calendar_clear",
    name: "看一眼日历",
    category: "mind",
    duration: 10,
    energyLevel: "low",
    instructions: [
      "打开明天的日历或待办。",
      "只看明天，不看整周。",
      "删除或移动一个不必要项目。",
      "写下明天最早出门或开始工作的时间。",
    ],
  },
  {
    id: "mod_one_problem_page",
    name: "一页问题",
    category: "mind",
    duration: 20,
    energyLevel: "mid",
    instructions: [
      "在纸顶端写下一个正在烦的问题。",
      "左边写事实，右边写猜测。",
      "把猜测中没有证据的划掉。",
      "最后写一个能在 10 分钟内做的动作。",
    ],
  },
  {
    id: "mod_audio_note",
    name: "录一分钟语音",
    category: "mind",
    duration: 5,
    energyLevel: "low",
    instructions: [
      "打开录音软件。",
      "录 60 秒，说出现在最占脑子的事。",
      "录完后命名为今天日期。",
      "不要回放，直接保存。",
    ],
  },
  {
    id: "mod_box_breathing",
    name: "方块呼吸",
    category: "mind",
    duration: 6,
    energyLevel: "low",
    instructions: [
      "坐下，双脚踩地。",
      "吸气 4 秒，停 4 秒。",
      "呼气 4 秒，停 4 秒。",
      "重复 6 轮后喝一口水。",
    ],
  },
  {
    id: "mod_sort_three_tasks",
    name: "三件事排序",
    category: "mind",
    duration: 12,
    energyLevel: "low",
    instructions: [
      "写下脑中最吵的三件事。",
      "给每件事标上今天、明天或不用管。",
      "今天那件事再拆成一个 5 分钟动作。",
      "把另外两件事合上不看。",
    ],
  },
  {
    id: "mod_gratitude_plain",
    name: "写三件还行",
    category: "mind",
    duration: 8,
    energyLevel: "low",
    instructions: [
      "打开纸或备忘录。",
      "写下今天三个没有变坏的具体东西。",
      "每条不超过 12 个字。",
      "写完后不要扩写分析。",
    ],
  },
  {
    id: "mod_read_old_message",
    name: "读旧消息",
    category: "mind",
    duration: 12,
    energyLevel: "low",
    instructions: [
      "打开一个让你感到稳定的聊天记录。",
      "往前翻到一段普通对话。",
      "只读 5 分钟，不回复也不解释。",
      "读完后关闭聊天窗口。",
    ],
  },
  {
    id: "mod_playlist_label",
    name: "建一个歌单",
    category: "mind",
    duration: 18,
    energyLevel: "low",
    instructions: [
      "新建一个歌单，名字用今天日期。",
      "加入 5 首你今晚能听完的歌。",
      "不要找新歌，只从收藏里选。",
      "播放第一首，然后把手机放远。",
    ],
  },
  {
    id: "mod_photo_delete",
    name: "删二十张照片",
    category: "mind",
    duration: 15,
    energyLevel: "low",
    instructions: [
      "打开相册最近项目。",
      "从最新照片开始向前看。",
      "删除 20 张截图、重复图或模糊照片。",
      "删除后立刻退出相册。",
    ],
  },
  {
    id: "mod_one_email",
    name: "处理一封邮件",
    category: "mind",
    duration: 12,
    energyLevel: "mid",
    instructions: [
      "打开邮箱，只搜索一封需要处理的邮件。",
      "读完后决定回复、归档或删除。",
      "如果回复，只写三句话以内。",
      "处理完立刻关闭邮箱。",
    ],
  },
  {
    id: "mod_worry_window",
    name: "担心窗口",
    category: "mind",
    duration: 15,
    energyLevel: "low",
    instructions: [
      "设置 10 分钟计时器。",
      "把所有担心写成问题句。",
      "每个问题后面写一个最小下一步。",
      "计时结束后把纸合上。",
    ],
  },
  {
    id: "mod_decision_two_options",
    name: "二选一决定",
    category: "mind",
    duration: 10,
    energyLevel: "low",
    instructions: [
      "写下正在纠结的两个选项。",
      "给每个选项写一个今晚会产生的结果。",
      "选择阻力更小的一个。",
      "把另一个选项写到明天再看。",
    ],
  },
  {
    id: "mod_close_open_loops",
    name: "关三个小循环",
    category: "mind",
    duration: 20,
    energyLevel: "mid",
    instructions: [
      "写下三个 5 分钟内能结束的小事。",
      "按从简单到难排序。",
      "逐个完成，每完成一个打勾。",
      "第三个完成后停止，不继续加任务。",
    ],
  },
  {
    id: "mod_sleep_boundary",
    name: "睡前边界",
    category: "mind",
    duration: 15,
    energyLevel: "low",
    instructions: [
      "写下今晚停止工作的时间。",
      "把电脑合上或退出工作软件。",
      "把明天要继续的事项写一行。",
      "关闭主灯，只留一盏小灯。",
    ],
  },
];
